os:
  - linux
  - osx
sudo: false

dist: trusty
osx_image: xcode8.2

env:
  matrix:
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__COVERAGE=ON -DCMAKE_BUILD_TYPE=debug" COVERALLS=yes
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS=""
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_OPENSSL=ON"
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_THREAD_SUPPORT=ON"
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_DEBUG_MODE=ON"
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__DISABLE_MM_REPLACEMENT=ON"
    - EVENT_BUILD_METHOD=cmake EVENT_CMAKE_OPTIONS="-DEVENT__ENABLE_VERBOSE_DEBUG=ON"
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS=""
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS="--disable-openssl"
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS="--disable-thread-support"
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS="--disable-debug-mode"
    - EVENT_BUILD_METHOD=autotools EVENT_CONFIGURE_OPTIONS="--disable-malloc-replacement"

language: c
compiler:
  - gcc
  - clang

before_install:
  - if [ -n "$COVERALLS" ]; then
      pip install --user cpp-coveralls;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew uninstall libtool && brew install libtool;
      brew install openssl;
      brew install lcov;
      if [ "$CC" == "gcc" ]; then
        export CC=$(ls -t /usr/local/bin/gcc-?.?);
      fi

      export OPENSSL_ROOT=$(echo /usr/local/Cellar/openssl/*);
      export
        CMAKE_INCLUDE_PATH=$OPENSSL_ROOT/include
        CMAKE_LIBRARY_PATH=$OPENSSL_ROOT/lib;
      export
        CFLAGS=-I$CMAKE_INCLUDE_PATH
        LDFLAGS=-L$CMAKE_LIBRARY_PATH;
    fi

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    packages:
    - zlib1g-dev
    - libssl-dev
    - build-essential
    - automake
    - autoconf
    - cmake
    - lcov

script:
  # Copy paste from travis-ci/travis-build/lib/travis/build/templates/header.sh
  # In attempt to make travis_wait works under OSX
  - ANSI_RED="\033[31;1m"
  - ANSI_GREEN="\033[32;1m"
  - ANSI_RESET="\033[0m"
  - ANSI_CLEAR="\033[0K"
  - travis_wait() {
      local timeout=$1;
      if [[ $timeout =~ ^[0-9]+$ ]]; then
        shift;
      else
        timeout=20;
      fi;

      local cmd="$@";
      local log_file=travis_wait_$$.log;

      $cmd &>$log_file &
      local cmd_pid=$!;

      travis_jigger $! $timeout $cmd &
      local jigger_pid=$!;
      local result;

      {
        wait $cmd_pid 2>/dev/null;
        result=$?;
        ps -p$jigger_pid &>/dev/null && kill $jigger_pid;
      };

      if [ $result -eq 0 ]; then
        echo -e "\n${ANSI_GREEN}The command $cmd exited with $result.${ANSI_RESET}";
      else
        echo -e "\n${ANSI_RED}The command $cmd exited with $result.${ANSI_RESET}";
      fi;

      echo -e "\n${ANSI_GREEN}Log:${ANSI_RESET}\n";
      cat $log_file;

      return $result;
    }
  - travis_jigger() {
      local cmd_pid=$1;
      shift;
      local timeout=$1;
      shift;
      local count=0;

      echo -e "\n";

      while [ $count -lt $timeout ]; do
        count=$(($count + 1));
        echo -e "Still running ($count of $timeout): $@";
        sleep 60;
      done;

      echo -e "\n${ANSI_RED}Timeout (${timeout} minutes) reached. Terminating \"$@\"${ANSI_RESET}\n";
      kill -9 $cmd_pid;
    }
  - if [ "$EVENT_BUILD_METHOD" = "autotools" ]; then
      ./autogen.sh &&
      ./configure $EVENT_CONFIGURE_OPTIONS &&
      make &&
      travis_wait 30 make -j20 verify;
    fi
  - if [ "$EVENT_BUILD_METHOD" = "cmake" ]; then
      mkdir build &&
      cd build &&
      cmake .. $EVENT_CMAKE_OPTIONS &&
      cmake --build . &&
      CTEST_PARALLEL_LEVEL=20
      CTEST_OUTPUT_ON_FAILURE=1
      travis_wait 30
      cmake --build . --target verify;
    fi

after_script:
  - if [ -n "$COVERALLS" ]; then
      coveralls
        --build-root .
        --root ..
        --exclude test
        --exclude sample
        --exclude cmake
        --exclude build/CMakeFiles/CheckTypeSize
        --exclude build/CMakeFiles/CompilerIdC
        --gcov-options '\-lp';
    fi

notifications:
  irc: "irc.oftc.net#libevent"
