version: 2.1.5.{build}
shallow_clone: true

os: Visual Studio 2015

build:
  verbosity: detailed

environment:
  global:
    CYG_ROOT: C:/MinGW/msys/1.0
  matrix:
    - EVENT_BUILD_METHOD: "autotools"
      EVENT_CONFIGURE_OPTIONS: ""
    - EVENT_BUILD_METHOD: "autotools"
      EVENT_CONFIGURE_OPTIONS: "--disable-openssl"
    - EVENT_BUILD_METHOD: "autotools"
      EVENT_CONFIGURE_OPTIONS: "--disable-thread-support"
    - EVENT_BUILD_METHOD: "autotools"
      EVENT_CONFIGURE_OPTIONS: "--disable-debug-mode"
    - EVENT_BUILD_METHOD: "autotools"
      EVENT_CONFIGURE_OPTIONS: "--disable-malloc-replacement"
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: ""
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: "-DEVENT__DISABLE_OPENSSL=ON"
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: "-DEVENT__DISABLE_THREAD_SUPPORT=ON"
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: "-DEVENT__DISABLE_DEBUG_MODE=ON"
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: "-DEVENT__DISABLE_MM_REPLACEMENT=ON"
    - EVENT_BUILD_METHOD: "cmake"
      EVENT_CMAKE_OPTIONS: "-DEVENT__ENABLE_VERBOSE_DEBUG=ON"
init:
  - git config --global core.autocrlf true
  - 'echo Building libevent %version% for Windows'
  - 'echo System architecture: %PLATFORM%'
  - 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
  - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
  - 'echo Repo build commit is: %APPVEYOR_REPO_COMMIT%'
  - 'echo Cygwin root is: %CYG_ROOT%'
install:
  - appveyor DownloadFile https://strcpy.net/packages/Win32OpenSSL-1_0_2a.exe
  - Win32OpenSSL-1_0_2a.exe /silent /verysilent /sp- /suppressmsgboxes
build_script:
  - cmd: >-
      if "%EVENT_BUILD_METHOD%" == "autotools" (
        echo "C:\MinGW   /mingw" >%CYG_ROOT%/etc/fstab
        set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
        C:\MinGW\bin\mingw-get install autotools autoconf automake python
        %CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null;mount C:/MinGW /mingw; bash -x ./autogen.sh; ./configure $EVENT_BUILD_METHOD; make; make verify"
      ) else (
        md build
        cd build
        cmake .. $env:EVENT_CMAKE_OPTIONS
        cmake --build .
        ctest --output-on-failure
      )
cache:
  - C:\OpenSSL-Win32
