version: 2.1.5.{build}
shallow_clone: true

os: Visual Studio 2015

build:
  verbosity: detailed

init:
  - 'echo Building libevent %version% for Windows'
  - 'echo System architecture: %PLATFORM%'
  - 'echo Repo build branch is: %APPVEYOR_REPO_BRANCH%'
  - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
install:
  - appveyor DownloadFile https://strcpy.net/packages/Win32OpenSSL-1_0_2a.exe 
  - Win32OpenSSL-1_0_2a.exe /silent /verysilent /sp- /suppressmsgboxes
build_script:
  - md build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
